### ------ requester VPC Variables ------ ###
requestor_vpc_region       = "us-east-1"
environment                = "test"
requester_vpc_cidr         = "10.0.0.0/16"
requester_vpc_name         = "requester-vpc"
requester_subnet1_cidr     = "10.0.0.0/24"
requester_subnet1_name     = "requester-subnet-1"
requester_subnet1_az       = "us-east-1a"
requester_subnet2_name     = "requester-subnet-2"
requester_subnet2_cidr     = "10.0.1.0/24"
requester_subnet2_az       = "us-east-1b"
requester_rt_name          = "requester-route-table"
requester_vpc_pub_sub_cidr = "10.0.2.0/24"
requester_ami_id           = "ami-0554aa6767e249943"
instance_type              = "t2.micro"


### ------ acceptor VPC Variables ------ ###
acceptor_region         = "us-west-2"
acceptor_cidr           = "10.10.0.0/16"
acceptor_vpc_name       = "acceptor-vpc"
acceptor_subnet1_cidr   = "10.10.0.0/24"
acceptor_subnet1_name   = "acceptor-subnet-1"
acceptor_subnet1_az     = "us-west-2a"
acceptor_subnet2_name   = "acceptor-subnet-2"
acceptor_subnet2_cidr   = "10.10.1.0/24"
acceptor_subnet2_az     = "us-west-2b"
acceptor_rt_name        = "acceptor-route-table"
acceptor_pub_sub_cidr   = "10.10.2.0/24"
map_public_ip_on_launch = false
acceptor_ami_id         = "ami-04999cd8f2624f834"