name: Terraform Cleanup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environrment"
        required: true
        default: "test"
        type: environment
      module_path:
        description: 'Path to the Terraform module'
        required: true
        default: 'VPC-Peering/Modules/single-vpc-to-vpc'
      aws_region:
        description: 'AWS Region for the Terraform module'
        required: true
        default: 'us-east-1'

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.module_path }}

    env:
      TFLINT_VERSION: '0.46.1'  
      TFSEC_VERSION: '1.28.1' 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_REGION: ${{ github.event.inputs.aws_region }} 

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v4

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.aws_region }} 

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "latest"

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      run: terraform destroy -auto-approve 