name: Trivy Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write

jobs:
  trivy:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Run Tricy vulnerabiltiy scanner in repo mode
       uses: aquasecurity/trivy-action@0.28.0
       with:
         scan-type: 'fs'
         scan-path: '.'
         severity: 'CRITICAL'
         format: 'sarif'
         output: 'trivy-results.sarif'
         ignore-unfixed: true
    
     - name: Upload Trivy scan results to GitHub Security tab
       uses: github/codeql-action/upload-sarif@v3
       with:
        sarif_file: 'trivy-results.sarif'
#

  iac_scan:
    name: iac_scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          iac-type: 'terraform'
          iac-policy: ''
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'  # make sure to use the same output file name
          exit-code: '1'
          severity: 'CRITICAL'
          

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif' # make sure to use the same output file name