name: Trivy Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  packages: write

jobs:
  iac_scan:
    name: iac_scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Trivy
        run: |
          trivy config --update
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'  # make sure to use the same output file name
          exit-code: '1'
          severity: 'CRITICAL'
          

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif' # make sure to use the same output file name